import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, parse } from "node:path";
import { toKebabCase } from "./naming";

/** Output flavor for the generated files. */
export type CodeStyle = "cjs" | "esm" | "ts";

export interface GenerateOptions {
  /** Raw queue name as typed by the user (kebab-cased for the folder + queue name). */
  name: string;
  /** Directory the queue folder is created under. Default: `./queues`. */
  dir?: string;
  /** Force a specific code style. Default: auto-detected from the nearest package.json. */
  style?: CodeStyle;
  /** Also emit a `config.*` with concurrency/retry defaults. Default: false. */
  withConfig?: boolean;
  /** Overwrite existing files instead of erroring. Default: false. */
  force?: boolean;
}

export interface GenerateResult {
  /** The resolved queue name (kebab-case). */
  queueName: string;
  /** Absolute path to the created queue folder. */
  folder: string;
  /** Absolute paths of files written. */
  files: string[];
  style: CodeStyle;
}

/** Turn a queue name into a safe JS identifier for the processor function. */
function toIdentifier(name: string): string {
  const camel = toKebabCase(name)
    .split("-")
    .filter(Boolean)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
  const ident = /^[a-zA-Z_]/.test(camel) ? camel : `q${camel}`;
  return `${ident || "queue"}Processor`;
}

/**
 * Detect the code style for a target directory by walking up to the nearest
 * `package.json`: `"type": "module"` → ESM, otherwise CJS. (TS is opt-in.)
 */
export function detectStyle(dir: string): CodeStyle {
  let current = existsSync(dir) ? dir : dirname(dir);
  const { root } = parse(current);
  for (;;) {
    const pkg = join(current, "package.json");
    if (existsSync(pkg)) {
      try {
        const json = JSON.parse(readFileSync(pkg, "utf8")) as { type?: string };
        return json.type === "module" ? "esm" : "cjs";
      } catch {
        return "cjs";
      }
    }
    if (current === root) return "cjs";
    current = dirname(current);
  }
}

const ext: Record<CodeStyle, string> = { cjs: ".js", esm: ".js", ts: ".ts" };

/** Render the processor file source for a queue. */
export function renderProcessor(queueName: string, style: CodeStyle): string {
  const fn = toIdentifier(queueName);
  const header =
    `// Job processor for the "${queueName}" queue — generated by \`bullmq-auto --generate\`.\n` +
    `//\n` +
    `// bullmq-autoqueue auto-discovers this folder at startup: the Queue, its Worker,\n` +
    `// and the Bull Board dashboard entry are all created for you — no central\n` +
    `// registry to edit. Add a sibling \`config${ext[style]}\` to tune concurrency/retries.\n` +
    `//\n` +
    `// Enqueue jobs with:  registry.add("${queueName}", "jobName", { /* data */ })\n\n`;

  if (style === "ts") {
    return (
      `import type { Job } from "bullmq";\n\n` +
      header +
      `export default async function ${fn}(job: Job) {\n` +
      `  const data = job.data;\n` +
      `  // TODO: implement the job logic for "${queueName}".\n` +
      `  return { ok: true };\n` +
      `}\n`
    );
  }
  if (style === "esm") {
    return (
      header +
      `export default async function ${fn}(job) {\n` +
      `  const data = job.data;\n` +
      `  // TODO: implement the job logic for "${queueName}".\n` +
      `  return { ok: true };\n` +
      `}\n`
    );
  }
  return (
    header +
    `module.exports = async function ${fn}(job) {\n` +
    `  const data = job.data;\n` +
    `  // TODO: implement the job logic for "${queueName}".\n` +
    `  return { ok: true };\n` +
    `};\n`
  );
}

/** Render the optional config file source for a queue. */
export function renderConfig(queueName: string, style: CodeStyle): string {
  const body =
    `{\n` +
    `  // name defaults to "${queueName}" (kebab-case of the folder); uncomment to pin.\n` +
    `  // name: "${queueName}",\n` +
    `  concurrency: 5,\n` +
    `  defaultJobOptions: {\n` +
    `    attempts: 3,\n` +
    `    backoff: { type: "exponential", delay: 1000 },\n` +
    `    removeOnComplete: 100,\n` +
    `    removeOnFail: 100,\n` +
    `  },\n` +
    `}`;
  if (style === "ts") {
    return `import { defineConfig } from "bullmq-autoqueue";\n\nexport default defineConfig(${body});\n`;
  }
  if (style === "esm") {
    return `export default ${body};\n`;
  }
  return `module.exports = ${body};\n`;
}

/**
 * Scaffold a new queue folder (`<dir>/<queue-name>/processor.*`, optionally
 * `config.*`). The queue is auto-registered with both BullMQ and Bull Board the
 * next time {@link loadQueues} runs — there is no central file to edit.
 *
 * @throws if the name is empty, or files exist and `force` is not set.
 */
export function generateQueue(options: GenerateOptions): GenerateResult {
  const queueName = toKebabCase(options.name).replace(/^-+|-+$/g, "");
  if (!queueName) {
    throw new Error(`bullmq-autoqueue: invalid queue name "${options.name}"`);
  }
  const dir = options.dir ?? join(process.cwd(), "queues");
  const style = options.style ?? detectStyle(dir);
  const folder = join(dir, queueName);

  const files: string[] = [];
  const targets: Array<[string, string]> = [
    [join(folder, `processor${ext[style]}`), renderProcessor(queueName, style)],
  ];
  if (options.withConfig) {
    targets.push([join(folder, `config${ext[style]}`), renderConfig(queueName, style)]);
  }

  if (!options.force) {
    for (const [path] of targets) {
      if (existsSync(path)) {
        throw new Error(`bullmq-autoqueue: ${path} already exists (use --force to overwrite)`);
      }
    }
  }

  mkdirSync(folder, { recursive: true });
  for (const [path, content] of targets) {
    writeFileSync(path, content, "utf8");
    files.push(path);
  }

  return { queueName, folder, files, style };
}
